repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: mixed-line-ending

-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
    -   id: isort
        files: src/
        args: ['--line-length', '120', '--profile', 'black']

-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    -   id: black
        files: src/
        args: ['--line-length', '120']

-   repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        files: src/
        args: ['--max-line-length', '120', '--ignore', 'Q000,D100,D205,D212,D400,D415,W605']